-- Add additional fields to Task table
ALTER TABLE "Task" ADD COLUMN IF NOT EXISTS tenant_id BIGINT REFERENCES "Tenant"(id) ON DELETE CASCADE;
ALTER TABLE "Task" ADD COLUMN IF NOT EXISTS start_date DATE;
ALTER TABLE "Task" ADD COLUMN IF NOT EXISTS estimated_hours NUMERIC(6,2);
ALTER TABLE "Task" ADD COLUMN IF NOT EXISTS actual_hours NUMERIC(6,2);
ALTER TABLE "Task" ADD COLUMN IF NOT EXISTS sort_order INTEGER DEFAULT 0;
ALTER TABLE "Task" ADD COLUMN IF NOT EXISTS complexity SMALLINT CHECK (complexity IN (1, 2, 3, 5, 8, 13, 21));
